### ISSUE TITLE
Split one-context.d scripts into libs and runtimes

### ISSUE THREAD

**Issue by dkelleher** [OpenNebula/addon-context-linux#101]
I just wanted to know your thoughts on splitting at least some of the scripts into libs and runtime components.  I'm making a script to handle policy based routing on the VM which reimplements many of the functions from the network script.  I'm happy to submit a PR I just figured I would start the conversation here first.

**Comment by vholer** [comment]
Hi. Makes sense, this would be really nice to have. Thanks.

**Comment by rsmontero** [comment]
we'll consider this done for now, and will tackle additional splits in the future
