### ISSUE TITLE
Optional password reset

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#102]
If no `PASSWORD*` is specified, the user's password on the instance is always reset to '*'

https://github.com/OpenNebula/addon-context-linux/blob/8f74136a5c6ba8d72c4400c803dea3013cf9be9a/src/etc/one-context.d/loc-20-set-username-password#L61-L63

This behavior should be possible to disable (e.g. if `PASSWORD_RESET=no`)

**Comment by kvaps** [comment]
@vholer why you used this asterisk?

In my opinninon you should remove any password here, like:
```
passwd -d "${USERNAME}"
```
or
```
usermod -p '' "${USERNAME}" 
```

This is classic unix way for set no password.
It's also gives good opportunity for logon into machine via graphic console if password is not set.

**Comment by vholer** [comment]
The provided options set the privileged account passwordless. From the security perspective, don't think this is a good default behavior.

**Comment by vholer** [comment]
> Also are you sure is that good idea for enable PASSWORD_RESET=YES option by default?
I believe it is. Similar way we should also fix the user's authorized keys.

> it is forces for store password in contextualization template 
Yes, but you still can have a pretty secure password hash, I dare to say unbreakable, in the contextualization data, if you do enough hashing rounds (e.g. mkpasswd -m sha-512 -R 2000000)

> Anytime they should to set PASSWORD_RESET=NO
I'm thinking about
1. separating all these defaults into own file on the guest
2. with option to override them from different configuration file on the guest
So, the person who is preparing images can easily override these defaults right in the image and not to depend on overrides from the contextualization.

**Comment by kvaps** [comment]
>The provided options set the privileged account passwordless. From the security perspective, don't think this is a good default behavior.

@vholer, thanks for answer, seems you really right.
If user will not take care of about securing vnc console, passwordless login can be really dangerous.

> 1. separating all these defaults into own file on the guest

Great idea!
I think we can move all scripts into `/usr/share/one-context.d/`, in `/etc/one-context.d/` leave only configuration for them

Thanks!

**Comment by 2autunni** [comment]
Hi,
on centos 7.4 
`usermod -p '*' "${USERNAME}" `  
doesn't works: the user can't login.
instead using 
`passwd -d "${USERNAME}"`
the result is to assign an empty password to the user

**Comment by vholer** [comment]
Hi @2autunni, that's expected behavior, not to unlock the account to be usable by anyone who has access to the VNC console. In new version, there will be a contextualization parameter `USERNAME_PASSWORD_RESET` to disable this behavior, already in Git. See the conversation above. Thank you, Vlastimil

**Comment by 2autunni** [comment]
HI @vholer, 
I'm confused... 
I'm using the last version of /etc/one-context.d/loc-20-set-username-password from the branch master.

I have a VM based on Centos 7.4, I stop it and  add to the conf:

```
USERNAME_PASSWORD_RESET = YES
```
before stopping the vm  /etc/shadow contains: 
`admin:<encrypt pwd>:17601:0:99999:7:::`

after rebooting the VM the /etc/shadow  contains:
`admin:*:17601:0:99999:7:::`

so the user can't access to the VM via VNC console.

So the expected behavior when USERNAME_PASSWORD_RESET is true is to lock the user?

**Comment by 2autunni** [comment]
Thank you @vholer.

I misunderstood the use of `USERNAME_PASSWORD_RESET`
