### ISSUE TITLE
Problems with one-context 5.4.2-1.deb on Ubuntu 8.04

### ISSUE THREAD

**Issue by iansangines** [OpenNebula/addon-context-linux#103]
I'm trying to contextualize an Ubuntu 8.04 Hardy for using it in Open Nebula. 
The main problem is that once i'm installing the package one-context_5.4.2-1.deb there is many dependency problems which I can not solve because of the Ubuntu version.

I attach you the error in console:
![2018-01-31_131649](https://user-images.githubusercontent.com/2512182/35622690-0d266a7a-0689-11e8-8fef-275cd07ee7fe.png)

I tried to upgrade the ubuntu version, but I need ubuntu 8 release because of the system requirements.

Is there any suitable one-context package version for ubuntu 8?
Is there any other way to fix it?

Thaks!

**Comment by vholer** [comment]
I don't think there is a compatible package for such old Ubuntu version. But, if this is the only problem, unmet dependencies, I believe you can ignore them. The missing packages aren't necessary for the core functionality(*). Problem is more if all the scripts around are backward compatible, I don't think so.

(*)You can also build your own package by removing the missing packages from the dependencies here:
https://github.com/OpenNebula/addon-context-linux/blob/fb9276351ae6d7e43e243b142e8cd9429b00c1d5/targets.sh#L87
and follow the build steps https://github.com/OpenNebula/addon-context-linux#build-own-package

**Comment by iansangines** [comment]
Finally I installed the package without that dependencies. Now the problem is that when instantiating the VM, on boot time says 'Error: No contextualization found'.

![image](https://user-images.githubusercontent.com/2512182/35677039-70d84b18-074e-11e8-80bc-c26c16e99ea7.png)

There are any possible changes in the scripts that I can do to make it work?

**Comment by vholer** [comment]
You can try to run the contextualization manually from the command line:

```
DEBUG=yes /usr/sbin/one-contextd
```

and, check the script above and make necessary changes to make it working. In your case the contextualization CD-ROM hasn't been found, please check the output of:

```
blkid -l -t LABEL="CONTEXT" -o device
```

maybe change it to search just by filesystem???

```
blkid -l -t TYPE=iso9660 -o device
```

or, for testing purposes simply hardcode the device name here:

https://github.com/OpenNebula/addon-context-linux/blob/fb9276351ae6d7e43e243b142e8cd9429b00c1d5/src/usr/sbin/one-contextd#L141

having just, for example:

```
local dev_context='/dev/sr0'
```

Just ideas...

**Comment by iansangines** [comment]
I've already done that and finally works!
The problem was that dev_context var, which hardcoded works.

The other two solutions will help me for shure with the next machines. Thank you very much!
