### ISSUE TITLE
Add log to context scripts execution

### ISSUE THREAD

**Issue by jfontan** [OpenNebula/addon-context-linux#11]
Error and debug messages should be written to a log file for easier debugging.

**Comment by baby-gnu** [comment]
Hello,

Another inspiration with my [liblog.sh](http://git.baby-gnu.net/gitweb/?p=user/dad/shell-libs.git;a=blob;f=lib/liblog.sh) from my recently Git'ed [shell-libs](http://git.baby-gnu.net/gitweb/?p=user/dad/shell-libs.git).

Regards.

**Comment by vholer** [comment]
Fixed by https://github.com/OpenNebula/addon-context-linux/commit/93cb488ffdd66f3360a1fe1235807d17be51af6d. Now we have a simple logging in main **one-contextd**
https://github.com/OpenNebula/addon-context-linux/blob/master/src/usr/sbin/one-contextd#L38
