### ISSUE TITLE
full contextualization is run on each boot when /var/run on tmpfs

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/addon-context-linux#111]
At least on Debian 9 and CentOS 7 _/var/run_ is a symlink to _/run_ which is a tmpfs mount so the content of _/var/run/one-context_ does not persist on VM reboot.

Tried to alter _RUNTIME_DIR_ environment variable to point to a more persistent path but  _/var/run/one-context/_ path is hard-coded in some files in _/etc/one-context.d/*_ rendering the idea useless.

**Comment by vholer** [comment]
Hello @atodorov-storpool. Yes, having the contextualization run on each boot, having the state files on ephemeral locations, was an intention. The way to disable (particular) recontextualizations would be through the configuration https://github.com/OpenNebula/addon-context-linux/issues/105 (in the future). Can you provide more feedback about that or may I consider the #105 will fix your use-case? Thank you, Vlastimil

**Comment by atodorov-storpool** [comment]
Hi @vholer,
It sounds OK if the proposed solution in #105 will provide an option to change RUNTIME_DIR (and get rid of the hard-coded paths to /var/run.

Currently I've replaced manually the hard-coded paths but it is not convenient task to do on each update of the image templates :)

**Comment by vholer** [comment]
Thank you. I put a note about that into the issue #105. Please, subscribe there since I'm going to close this one. Having `RUNTIME_DIR` configurable should be possible. Best regards, Vlastimil
