### ISSUE TITLE
loc-05-grow-rootfs may be not desired

### ISSUE THREAD

**Issue by ZleFox** [OpenNebula/addon-context-linux#115]
Hello, 
Most VMs are one partition and the root is  where your disk space you want to be, but there are some with separate partitions where the root partition is not where you store most of your data - you may need it in var or home. This scenario is commonly used with LVM. So there the automatic pv resize is useful, but the automatic lvresize is not. As the rootfs is not online shrinkable, you can not distribute your free space among the LVs you need. 
Perhaps you may tweak this so it is configurable via CONTEXT.

**Comment by sndrsmnk** [comment]
This hit me too!  I _want_ to keep some unassigned space in my VG to use with LVM snapshots.
An option for this, to toggle it off, would be really great.
