### ISSUE TITLE
Growing root volume doesn't work on Minimal Ubuntu

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#116]
Identified problems:

1. Proc mounts doesn't contain valid root volume device:

```
# cat /etc/mtab | grep ' / ' | grep -v '^rootfs'
/dev/root / ext4 rw,relatime,data=ordered 0 0
# ls -la /dev/root
ls: cannot access '/dev/root': No such file or directory
```

It would be good to start using `findmnt` instead, e.g.:

```
# findmnt -ln -o SOURCE,FSTYPE /
/dev/vda1 ext4
# findmnt -ln -o SOURCE,FSTYPE /
/dev/mapper/centos_nessos-root xfs
```

2. Non-LVM device name always stripped

This part:

https://github.com/OpenNebula/addon-context-linux/blob/2908e045080947bf80e0c4a29363e96811802871/src/etc/one-context.d/loc-05-grow-rootfs#L16

always removes last character from the device name, no matter if it is a partition number or not. Should strip only all trailing number. Error from log:

```
Jul 12 10:02:55 ubuntu one-contextd[457]: Script loc-05-grow-rootfs: Starting ...
Jul 12 10:02:55 ubuntu one-contextd[486]: Script loc-05-grow-rootfs output: FAILED: /dev/roo: does not exist
Jul 12 10:02:55 ubuntu one-contextd[486]: resize2fs 1.42.13 (17-May-2015)
Jul 12 10:02:55 ubuntu one-contextd[486]: open: No such file or directory while opening /dev/root
Jul 12 10:02:55 ubuntu one-contextd[487]: Script loc-05-grow-rootfs: Finished with exit code 1
```

**Comment by vholer** [comment]
Just a note: The difference in the contextualized sizes of the base and minimal appliances would be:
- Ubuntu 16.04: base 306 MiB vs. minimal 195 MiB
- Ubuntu 18.04: base 351 MiB vs. minimal 212 MiB

**Comment by tubemeister** [comment]
There are still too many assumptions in this, even after your suggestions for improvement.

My root fs lives on /dev/mapper/LVM0-root, which readlink translates to /dev/dm-0, which breaks the assumption that deleting the trailing digit gets you a valid $DISK.

My /etc/fstab has UUIDs in it, which breaks the "grep mapper" LVM detection.

The "parted $DISK print" command hangs on interactive user input:

parted /dev/vda print
Warning: Not all of the space available to /dev/vda appears to be used, you can fix the GPT to use all of the space (an extra 12582912 blocks) or continue with the current setting? 
Fix/Ignore?

I've put in the following to test with:

```
if [ $(grep ' / ' /etc/mtab | grep -v '^rootfs' | grep LVM |wc -l) -ne 0 ]; then
  LVM="yes"

```
With this and fixing the GPT before running the script, the rest works for me.

**Comment by vholer** [comment]
Following fixes applied:
- 61901fd66ee38fb38d360b06559cc219e4c0f27b (detect LVM / rootfs device)
- 337b52c08a8dd71000148cf5d1dbf02bad6cc80a (non-interactive parted)

Closing.
