### ISSUE TITLE
Debian Network DHCP and/or contextual patch

### ISSUE THREAD

**Issue by sgocken** [OpenNebula/addon-context-linux#117]
This patch configures an interface with a blank $IP from context as dhcp instead of leaving it unconfigured and unusable.

I have tested with multiple interfaces with some having context and some not. Config comes out as expected.
I have not done any testing with IPv6, except that IPv6 will come up on the interface and will get an IP from either DHCPv6 or RA.

[loc-10-network##deb.one.patch.txt](https://github.com/OpenNebula/addon-context-linux/files/2242676/loc-10-network.deb.one.patch.txt)

**Comment by vholer** [comment]
The change will require extra option to enable DHCP, not just check if IP is missing in the context.

Duplicate of #86. Closing.
