### ISSUE TITLE
loc-16-gen-env permissions

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/addon-context-linux#122]
Hi,

from what I see the script ```loc-16-gen-env``` generates ```/var/run/one-context/one_env```, the file is later used to access the variables from the context ISO.
The permissions on that file are 644. It's still protected by the 700 perms on ```/var/run/one-context```, but it would probably be good to also have a 400 on the actual file.

**Comment by vholer** [comment]
Fixed, thank you.
