### ISSUE TITLE
RedHat Network config issue

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/addon-context-linux#123]
Hello, I hit bug with network config on redhat systems. If there is existing config, for ex. ifcfg-eth0 it will be renamed to ifcfg-eth0.old and new ifcfg-eth0 will be created. Problem is, that network service reads also ifcfg-eth0.old config. In my case it assing two IPv6 addresses, old one and new one and system by default use old one as source address and therefore anti spoofing rules block ipv6 traffic. I have to manually remove *.old config and reboot machine...

**Comment by vholer** [comment]
Hello. Not sure about which version/part you are talking about. We don't back up the existing configuration as files with a suffix `.old`. When context package is installed, it removes the existing configuration and when the configuration is refreshed, it only replaces the related interfaces. Please provide some more details. Thank you.

**Comment by feldsam** [comment]
probably I have older version of this package installed? I also forgot on which VM it was :( so I can not check.

**Comment by vholer** [comment]
Probably you have some legacy / custom content in `/etc/one-context.d/` ? Please ensure there are only files managed by the packaging system, better do a clean installation. Closing, reopen in case you find the problem persisting. Thank you.

**Comment by feldsam** [comment]
HI, I found it. VM have installed

one-context.noarch                    5.0.2-1                          installed

and  ifcfg-eth0.old apears in network-scripts

**Comment by nassetre** [comment]
Hi, I have the same problem. some times without reboot, I find ifcfg-enp0s3.old (also ifcfg-team0-enp0s8.old, ifcfg-team0-enp0s9.old and ifcfg-team0.old) automatically created in /etc/sysconfig/network-scripts directory. After reboot, network and teamd@team0 services are down. I can restart network service by deleting the .old files but can not start the teamd@team0 service. I'm preparing RHCE and will pass in 2 days, I'm afraid to meet this problem in the exam.
Please help.
