### ISSUE TITLE
rpm/deb packages should require bind-utils (or whatever provides `host` command)

### ISSUE THREAD

**Issue by jtriley** [OpenNebula/addon-context-linux#13]
Used by `05-hostname` script - without the `host` command the `DNS_HOSTNAME=1` functionality doesn't work.

**Comment by jmelis** [comment]
Sorry for the seriously long delay... we don't want to add dependencies to this package. The main reason is that we want to be able to install this package even if there's no internet available. If the package has deps it won't be possible to install it.

We are thinking about creating a second empty package that has only the dependencies. However for the momento we are not going to do it.

In any case thanks for pointing this out!
