### ISSUE TITLE
FreeBSD contextualization

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#131]
We have already merged #120 with initial FreeBSD support.
This is a tracking issue for further FreeBSD contextualization fixes and improvements.

**Comment by trenton42** [comment]
Would you also update the README.md for any FreeBSD specific information (version support, building, etc)? Thank you for this!

**Comment by Avatat** [comment]
@vholer, could you give us an example, how to build this for FreeBSD and what are the dependencies?
Basically, FreeBSD doesn't have Bash, but even with Bash installed, there is an error:
```
# bash generate.sh
find: -printf: unknown primary or operator
```
FreeBSD's `find` doesn't have `-printf` primary.

**Comment by vholer** [comment]
@Avatat, package creation isn't adapted for the FreeBSD. It's expected to be run on Linux:

```
$ TARGET=freebsd ./generate.sh
DEPRECATION NOTICE: XZ::StreamWriter#close will automatically close the wrapped IO in the future. Use #finish to prevent that.
	/home/myuser/.gem/ruby/gems/ruby-xz-0.2.3/lib/xz/stream_writer.rb:185:in `initialize'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/package/freebsd.rb:85:in `new'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/package/freebsd.rb:85:in `block in output'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/package/freebsd.rb:84:in `open'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/package/freebsd.rb:84:in `output'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/command.rb:487:in `execute'
	/home/myuser/.gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
	/home/myuser/.gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	/home/myuser/.gem/ruby/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
	/home/myuser/bin/fpm:23:in `load'
	/home/myuser/bin/fpm:23:in `<main>'
Created package {:path=>"out/one-context-5.7.80_0.20190204git3533cf6.txz"}
one-context-5.7.80_0.20190204git3533cf6.txz
```

Since FPM doesn't respect the dependencies, package should be installed the following way for now:

```
pkg install -y curl bash sudo base64 ruby open-vm-tools-nox11
pkg install -y one-context-[0-9]*.txz
```

**Comment by vholer** [comment]
> Would you also update the README.md for any FreeBSD specific information (version support, building, etc)? Thank you for this!

@trenton42, we test the FreeBSD 11.2 and 12.0 (should be now mentioned on the main page). About the building, just use `TARGET=freebsd ./generate.sh` on Linux as stated above. For sure the `generate.sh` can be adapted to run on FreeBSD as well, but for now, it wasn't a priority. Feel free to contribute back!

We are going to release the beta packages soon, incl. the updates in the documentation.

**Comment by trenton42** [comment]
@vholer Thank you for updating that! I missed the `TARGET=freebsd` when I was looking through the scripts.

**Comment by Avatat** [comment]
@vholer, thank you for the instructions and explanations!

I will try to adapt generate.sh for FreeBSD systems and will make Pull Request when I have done.

**Comment by vholer** [comment]
As we are near the release of stable 5.8.0 packages, I'm closing this issue.

Further FreeBSD fixes/improvements will be handled by their own issues.
