### ISSUE TITLE
contextualization triggered on LXD Host VM when starting a container managed by OpenNebula

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/addon-context-linux#138]
Here is my setup:

Instantiated two OpenNebula VMs to test ONE-5.7.80 using templates from the Marketplace.

First VM1 is with one-5.6.80 as frontend (running CentOS7). The second VM2 is installed/configured as a LXD host running Ubuntu 18.04, added as a HOST to be managed by the first VM.

The following log was observed when an LXD container is instantiated on VM2 (that is playing as a LXD host)

> Jan 19 15:44:51 one-lxdhost systemd[1]: Started Session 79 of user oneadmin.
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.302853] EXT4-fs (loop0): recovery complete
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.303358] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.407199] ISO 9660 Extensions: Microsoft Joliet Level 3
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.407238] ISO 9660 Extensions: Microsoft Joliet Level 3
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.409665] ISO 9660 Extensions: RRIP_1991A
> Jan 19 15:44:53 one-lxdhost kernel: [ 1116.498981] audit: type=1400 audit(1547912693.282:29): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-one-1_</var/lib/lxd>" pid=12657 comm="apparmor_parser"
> Jan 19 15:44:53 one-lxdhost systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc, triggered by 12658 (lxd)
> Jan 19 15:44:53 one-lxdhost systemd[1]: Mounting Arbitrary Executable File Formats File System...
> Jan 19 15:44:53 one-lxdhost systemd[1]: Mounted Arbitrary Executable File Formats File System.
> Jan 19 15:44:54 one-lxdhost systemd[1]: Starting OpenNebula reconfiguration script...
> Jan 19 15:44:54 one-lxdhost one-contextd[12749]: Started for type all to reconfigure
> Jan 19 15:44:54 one-lxdhost one-contextd[12750]: Acquiring lock /var/run/one-context/one-context.lock
> Jan 19 15:44:54 one-lxdhost one-contextd[12752]: Acquired lock /var/run/one-context/one-context.lock
> Jan 19 15:44:54 one-lxdhost one-contextd[12756]: Mounting CD-ROM /dev/loop1 on /var/run/one-context/mount.UTe9Wl
> Jan 19 15:44:54 one-lxdhost one-contextd[12758]: Found context /var/run/one-context/mount.UTe9Wl/context.sh
> Jan 19 15:44:54 one-lxdhost one-contextd[12760]: Comparing /var/run/one-context/context.sh.8UEYpP and /var/run/one-context/context.sh.local for changes
> Jan 19 15:44:54 one-lxdhost one-contextd[12762]: New context with changes
> Jan 19 15:44:54 one-lxdhost one-contextd[12770]: Processing local scripts
> Jan 19 15:44:54 one-lxdhost one-contextd[12772]: Script loc-05-grow-rootfs: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12817]: Script loc-05-grow-rootfs output: NOCHANGE: partition 1 is size 125601759. it cannot be grown
> Jan 19 15:44:54 one-lxdhost one-contextd[12817]: resize2fs 1.44.1 (24-Mar-2018)
> Jan 19 15:44:54 one-lxdhost one-contextd[12817]: The filesystem is already 15700219 (4k) blocks long.  Nothing to do!
> Jan 19 15:44:54 one-lxdhost one-contextd[12818]: Script loc-05-grow-rootfs: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12820]: Script loc-10-network: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12843]: Script loc-10-network: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12845]: Script loc-10-network-pci: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12853]: Script loc-10-network-pci: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12855]: Script loc-11-dns: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12877]: Script loc-11-dns: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12879]: Script loc-14-mount-swap: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12888]: Script loc-14-mount-swap: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12890]: Script loc-16-gen-env: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12901]: Script loc-16-gen-env output: cat: /var/run/one-context/mount.UTe9Wl/token.txt: No such file or directory
> Jan 19 15:44:54 one-lxdhost one-contextd[12903]: Script loc-16-gen-env: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12906]: Script loc-20-set-username-password: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12921]: Script loc-20-set-username-password: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12923]: Script loc-22-ssh_public_key: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12928]: Script loc-22-ssh_public_key: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12930]: Script loc-24-ssh_host_key: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[12934]: Script loc-24-ssh_host_key: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[12937]: Script loc-30-console: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[13015]: Script loc-30-console: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13017]: Finished scripts processing
> Jan 19 15:44:54 one-lxdhost one-contextd[13020]: Comparing /var/run/one-context/context.sh.8UEYpP and /var/run/one-context/context.sh.network for changes
> Jan 19 15:44:54 one-lxdhost one-contextd[13023]: New context with changes
> Jan 19 15:44:54 one-lxdhost one-contextd[13033]: Processing network scripts
> Jan 19 15:44:54 one-lxdhost one-contextd[13035]: Script net-11-fix-loopback: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[13040]: Script net-11-fix-loopback: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13043]: Script net-15-hostname: Starting ...
> Jan 19 15:44:54 one-lxdhost dbus-daemon[3279]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.62' (uid=0 pid=13057 comm="hostnamectl set-hostname --static ds1lxd1 " label="unconfined")
> Jan 19 15:44:54 one-lxdhost systemd[1]: Starting Hostname Service...
> Jan 19 15:44:54 one-lxdhost dbus-daemon[3279]: [system] Successfully activated service 'org.freedesktop.hostname1'
> Jan 19 15:44:54 one-lxdhost systemd[1]: Started Hostname Service.
> Jan 19 15:44:54 one-lxdhost systemd-resolved[4496]: System hostname changed to 'ds1lxd1'.
> Jan 19 15:44:54 one-lxdhost systemd-hostnamed[13060]: Changed static host name to 'ds1lxd1'
> Jan 19 15:44:54 one-lxdhost one-contextd[13101]: Script net-15-hostname: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13103]: Script net-97-start-script: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[13111]: Script net-97-start-script: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13114]: Script net-98-execute-scripts: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[13121]: Script net-98-execute-scripts: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13123]: Script net-99-report-ready: Starting ...
> Jan 19 15:44:54 one-lxdhost one-contextd[13126]: Script net-99-report-ready: Finished with exit code 0
> Jan 19 15:44:54 one-lxdhost one-contextd[13127]: Finished scripts processing
> Jan 19 15:44:54 one-lxdhost one-contextd[13128]: Done
> Jan 19 15:44:54 one-lxdhost one-contextd[13129]: Unmounting /var/run/one-context/mount.UTe9Wl
> Jan 19 15:44:55 one-lxdhost one-contextd[13135]: Releasing lock /var/run/one-context/one-context.lock
> Jan 19 15:44:55 one-lxdhost systemd[1]: Started OpenNebula reconfiguration script.
> 

It is easy to spot that the *one-contextd* on the host was triggered when the container's contextualization was added via */dev/loop1*.

IMHO the contexualization should behave depending on the virtualization technology and in the kase of KVM it should look for CDROM dvices only */dev/sr0* and skip */dev/loop* accordingly.

Best Regards,
Anton Todorov

**Comment by vholer** [comment]
Thank you for the provided patch, @atodorov-storpool ! I have applied your change also to other udev configurations (to be in sync) and also filtered the `/dev/loop` from `blkid` output so the host doesn't try to mount wrong ISO (in case expected host recontextualization happens).
