### ISSUE TITLE
Incorrect postinstall script for FreeBSD target

### ISSUE THREAD

**Issue by MATPOCKuH** [OpenNebula/addon-context-linux#143]
Hello!
For freebsd target pkg/postinstall used as postinstall script:
```
POSTIN=${POSTINST:-pkg/postinstall}
```
But this script is a linux specific.

For pfsense another script specified:
```
POSTIN=${POSTINST:-pkg/postinstall.freebsd}
```

But pkg/postinstall.freebsd does not exists in repository.

**Comment by vholer** [comment]
Hello,

> But this script is a linux specific.
What is there Linux specific? It's a shared script for all, with code also for FreeBSD (at the bottom).

> For pfsense another script specified:
pfSense is just WIP. We don't mention pfSense support anywhere.

Thanks.

**Comment by vholer** [comment]
Closing this issue, leaving just #144
