### ISSUE TITLE
Review context package dependencies

### ISSUE THREAD

**Issue by dann1** [OpenNebula/addon-context-linux#145]
**Description**
Running [hostname contextualization](https://github.com/OpenNebula/addon-context-linux/blob/c8903abd743fb613353f85e716f4023fc3b30c93/src/etc/one-context.d/net-15-hostname#L14) fails on some distros from the LXD marketplace.

Ubuntu Xenial:

```
root@LXC_NAME:~# hostnamectl set-hostname --static oned
Failed to create bus connection: No such file or directory
```

Debian Buster:

```
root@LXCNAME:~# hostnamectl set-hostname --static oned
Could not set property: Failed to activate service 'org.freedesktop.hostname1': timed out (service_start_timeout=25000ms)
```

**To Reproduce**
Deploy any of the affected apps from the LXD marketplace.

**Expected behavior**
Hostname contextualzation should set the appropriate hostname

**Details**
 - Affected Component: Virtualization
 - Hypervisor: LXD
 - Version: 5.8.0

**Additional context**
The command Ubuntu bionic runs ok, also 16.04 - KVM image doesn't show issues.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Thanks a lot for the info!

**Comment by vholer** [comment]
I would say Ubuntu (and maybe other images) are missing much more services to be usable (e.g., `openssh-server`).

**Comment by dann1** [comment]
The container images from the public LXD servers are very minimal, we need to look for the distros we support context on and check for missing dependencies. Alpines don't even have bash

**Comment by vholer** [comment]
Bash is already a dependency of Alpine packages. Maybe you are installing them wrong.

Anyway, I'm changing the topic of this issue to review all the dependencies. The dbus PR is for now merged.

**Comment by vholer** [comment]
List of dependencies to configured (to be continually updated):
- SSH server (note: Alpine has multiple alternatives)

**Comment by dann1** [comment]
PRs for merge:
- [infra](https://github.com/OpenNebula/infra/pull/219) into master
- [one](https://github.com/OpenNebula/one/pull/3156) into master and 5.8 
- [development](https://github.com/OpenNebula/development/pull/575) into master and 5.8

**Comment by dann1** [comment]
I think we can close this since https://github.com/OpenNebula/one/issues/3189 and https://github.com/OpenNebula/infra/pull/344 showed good results for tests
