### ISSUE TITLE
Support ALT Linux

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#159]
Add support for ALT Linux contextualization with official package and Marketplace image.

**Please, place emoji on this initial comment in case you are interested in this feature. It allows us to track the level of interest. Thank you.**

**Comment by shaba** [comment]
What about your plans?

**Comment by vholer** [comment]
We have some changes proposal for the packages with updated dependencies and systemd-networkd renderer: https://github.com/OpenNebula/addon-context-linux/compare/master...feature-159. We got feedback that "above changes work". Merging this is easy and people could build unofficial package, to the official support the path is quite longer (we must prepare our build and testing for that platform and fix all functionality incompatibilities, e.g. I can see the networkd rendered lacks support for aliases).

Btw, one guy from ALT mentioned the regular rpmbuild (from CentOS) can't be used to build such package for ALT because of some incompatibilities. Our build is done via fpm (which internally triggers rpmbuild), it's done on a single CentOS system for all platforms, even Debian or FreeBSD. So, the requirement to build ALT package on ALT system would be an extra complexity in the process. Do you know more about these rpm format incompatibilities?

Anyway, I think we can make a progress in this and target 5.12. Rescheduled.

**Comment by vholer** [comment]
We have merged updates to support ALT Linux since upcoming 5.12 release. There will be a dedicated rpm package, also there will be Marketplace image with p9, both aligned with 5.12 release. Based on the tests it's behaving very well on KVM, we don't have image working on LXD on vCenter for now.
