### ISSUE TITLE
Setup timezone

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/addon-context-linux#165]
It would be nice to have ability to setup timezone in contextualization scripts

**Comment by vholer** [comment]
Reopening, pending tasks on our side:
- consider using timedatectl where possible (and use current file based approach)
- update ONE docs (https://github.com/OpenNebula/docs/blob/master/source/operation/references/template.rst#context-section)
- add tests

**Comment by kvaps** [comment]
Also consider to add `tzdata` to the package dependencies (eg. alpine have no tzdata installed from the beginning)

**Comment by kvaps** [comment]
**UPD:** most of packages in alpine uses strategy to be installed on demand. *Eg: openssl can be installed during the boot same way, if you need to decrypt apkovl file.* We can use the same strategy to run `apk add tzdata` if `TIMEZONE` variable is set

**Comment by vholer** [comment]
Similar concern we had with the Ruby dependencies for the OneGate (#125). I'm not happy with bringing all as hard dependencies, but more I don't like ad-hoc installing of something, as it requires working public networking. In case of timezone data, I would say we could avoid this dependency and leave it on the user who is building the image.

At least, the contextualization script should provide some error in the log if requested timezone is not defined. Right now, it would skip silently.

**Comment by vholer** [comment]
We have  support for timedatectl, we have tests, we have similar feature for Windows, we have updated docs. On Alpine, I'm not adding dependency on `tzdata`, leaving this completely on user who is building the image.

Closing.
