### ISSUE TITLE
Fedora LXD

### ISSUE THREAD

**Issue by alitvak69** [OpenNebula/addon-context-linux#169]
I tested both Fedora 29 and Fedora 30 under LXD.  Networking, setting hostname, vnc console doesn't work

I see log in  the root directory.  
images-fedora is not supported by OpenNebula context
Image doesn't even have ssh server daemon running so no remote access either even if network is working.

lxc ls
+--------+---------+------+------+------------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+--------+---------+------+------+------------+-----------+
| one-37 | RUNNING |      |      | PERSISTENT | 0         |
+--------+---------+------+------+------------+-----------+

**Comment by dann1** [comment]
For VNC, try [updating the vcnterm command](http://docs.opennebula.org/5.8/deployment/open_cloud_host_setup/lxd_driver.html#guest-issues) being executed.

For image contextualization, the code [isn't there yet](https://github.com/OpenNebula/one/issues/3178), however, you can try the following patch, test it and give us feedback about it.

The import procedure for fedora should be similar to CentOS, so, you can extend the import script and add a fedora procedure, it is located in the frontend, `/var/lib/one/remotes/datastore/lxd_downloader.sh`, here are the CentOS lines, so, it should be similar.

https://github.com/OpenNebula/one/blob/7f0863ea4998f486d1d2e7add6b2cba1fc3ac72e/src/datastore_mad/remotes/lxd_downloader.sh#L171-L203

**Comment by alitvak69** [comment]
Sorry if it is a stupid question,  I noticed that fedora lxd ha no ssh
server installed.  Will contextualizing fix it?

**Comment by dann1** [comment]
Currently not, however, during the import process it could be addedm like alpine does now or it could also be added as a [context package dependency](https://github.com/OpenNebula/addon-context-linux/issues/145#issuecomment-477944545)

**Comment by dann1** [comment]
Hi, we've [updated the code](https://github.com/OpenNebula/one/commit/1e23634420f86f73a360af1ce71561716a404525) to process fedora when importing the marketplace apps. Could you patch your setup and test it ?

**Comment by alitvak69** [comment]
Tested using fedora 30.  It looks much better.  In privileged mode, I got the hostname, ssh, and IP address.  I could log in remotely using my key and have internet access.

Thank you,

**Comment by dann1** [comment]
Weird [hostname isn't working for me](https://github.com/OpenNebula/one/issues/3178#issuecomment-509506277). Could you close this issue ? We can open new ones for specific situations.

**Comment by alitvak69** [comment]
It didn't work for me out of the box.  I made these changes to a template via a web interface
LXD_SECURITY_NESTING = "yes"
LXD_SECURITY_PRIVILEGED = "yes"
SCHED_DS_RANK = "FREE_MB"
SCHED_DS_REQUIREMENTS = "ID=\"101\""
SCHED_RANK = "-RUNNING_VMS"
SCHED_REQUIREMENTS = "CLUSTER_ID=\"100\""

Not sure if any were relevant to host but it showed up after I recreated a container.

Closing per your request.
