### ISSUE TITLE
Dependent packages for one-context on opensuse

### ISSUE THREAD

**Issue by atotala** [OpenNebula/addon-context-linux#175]
I am trying to install the one-context package on SUSE and it is asking for dependent packages.
can anyone tell me what are all dependent packages ?

**Comment by vholer** [comment]
SUSE package depends on following packages:
https://github.com/OpenNebula/addon-context-linux/blob/5.8.0/targets.sh#L102
(all are specified as an rpm package dependency, so your packager should resolve this dependency automatically and install required packages from the distribution repository).

Follow the installation steps for SUSE:
http://docs.opennebula.org/5.8/operation/vm_setup/kvm.html#opensuse
