### ISSUE TITLE
systemd one-context.service ordering doesn't seem correct

### ISSUE THREAD

**Issue by rbjorklin** [OpenNebula/addon-context-linux#179]
The systemd unit for `one-context.service` says it should run [After=multi-user.target](https://github.com/OpenNebula/addon-context-linux/blob/master/src/usr/lib/systemd/system/one-context.service%23%23systemd.one#L4) but at the same time it [wants to be a part of multi-user.target](https://github.com/OpenNebula/addon-context-linux/blob/master/src/usr/lib/systemd/system/one-context.service%23%23systemd.one#L13). This does not seem correct to me and I believe `multi-user.target` should be removed from the `After=` option.

**Comment by xorel** [comment]
I disagree. It's in `[Install]` section and thus it only says where the `one-context.service` symlink will be created when enabling the service.
