### ISSUE TITLE
ssh contextualisation should *not* overwrite authorized_keys file

### ISSUE THREAD

**Issue by jfontan** [OpenNebula/addon-context-linux#19]
By Nico Schottelius in http://dev.opennebula.org/issues/3931.

The problem with overwriting on (re-)boot is that every manual change is overwritten. This causes problems, because users are usually not aware of what opennebula is "doing to their VM".

I suggest to change it to append, if the key is not present. It can be a very simple script like if ! grep "$key" ~root/.ssh/authorized_keys; then echo $key >> ... ; fi

If the contextualisation packages are somewhere available in a version control repo, I can also create a pull request

**Comment by telmich** [comment]
Thanks a lot, @jfontan !
