### ISSUE TITLE
Support Ubuntu Focal 20.04

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/addon-context-linux#190]
Ubuntu Focal 20.04 won't ship with python 2 anymore. Current one-context depends on python, which is not available, python2-minimal is available but it would be best not to depend on a deprecated (EOL) python version anymore. What python2 specific functionality is need in one-context?

**Comment by vholer** [comment]
Looks like just some legacy dependency, I have removed it. Thanks.

We'll release updated packages before Focal gets stable release.
