### ISSUE TITLE
Ubuntu Focal (20.04) hangs while shutting down

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/addon-context-linux#197]
When OpenNebula-context (master) is installed on Ubuntu Focal (minimal install) it hangs while shutting down the VM. When OpenNebula-context is removed from the system this issue does not occur.

It seems to have to do with LVM. See screenshot
![one_context_ubuntu_focal_shutdown_issue](https://user-images.githubusercontent.com/6695474/76881025-d4932a00-6878-11ea-8774-41ea1afc03fd.png)

Any hints how to debug this? It's 100% reproducible.

**Comment by vholer** [comment]
Unfortunately, can't reproduce the issue. If this still happens (to you or anybody) with Ubuntu installations with most recent distr. packages and latest context packages, please reopen the issue. Closing for now.
