### ISSUE TITLE
Contextualize SSH user

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/addon-context-linux#21]
Hello,

I'm in the process of writing a patch to contextualize the user used to configure the ssh public key.

The idea is to avoid untraceable generic account like ```root```, so I'll proposed another pull request for ```sudo``` context script to create a local account with ```sudo``` permission.

I started with a ```${SSH_USER}``` variable, but I saw the ```${USERNAME}``` used for windows machines and I think reusing it here is better than creating a new one.

Tell me what do you think about this.

Regards.

**Comment by jfontan** [comment]
I also think that it's better to use the same variable name. Other things that you may have to take into account:

* `sudo` package is not installed in all images. I've seen this in some cloud images
* not all `sudoer` files allow users from a certain group to become root

**Comment by baby-gnu** [comment]
Thanks.

**Comment by baby-gnu** [comment]
The main issue is fixed by 0d8ae8d8489f6d378688d2ce5773381bd2f97085.
