### ISSUE TITLE
IP address & debian VM

### ISSUE THREAD

**Issue by dimv36** [OpenNebula/addon-context-linux#210]
Hi, I'm using debian 9 VM in OpenNebula 5.8.5, so, I'm installing context package to VM.
How can I specify IP address information, that will apply on VM?

**Comment by vholer** [comment]
You set the IP address in Sunstone when attaching the NIC.
Or, set it in the VM template `NIC = [ IP = "a.b.c.d", .... ]`. https://docs.opennebula.io/5.12/operation/references/template.html#network-section

Please use Community Forum (https://forum.opennebula.io) for questions related to how to use OpenNebula.
