### ISSUE TITLE
Selectable Network Configuration Renderers

### ISSUE THREAD

**Issue by jonathanmarsaud** [OpenNebula/addon-context-linux#227]
Hi,

I saw that you already have support for `networkd` for some type of distribution in `loc-10-network##networkd.one` and `targets.sh`. Debian is not a part of it, according to the `TAGS` variable in `targets.sh`.

We are managing a large range of distributions in our OpenNebula cluster in production, and so, we tend to favor **systemd-networkd** for all of them, as a common denominator.

So it will be much appreciated if, as an officially supported option to avoid forking/customizing **addon-context-linux**, if we can choose to render `deb` system with `networkd` instead of the traditional `/etc/network/interfaces`.

Default value for this option can be traditional `/etc/network/interfaces` as this is always the official way for Debian, but it will permit to advanced user to just use your already existing code to render networkd on Debian.

Regards,

**Comment by vholer** [comment]
We'll hijack this issue as an umbrella for several features implemented as well as part of the changes:

- All context packages will have all supported network configurators (which we call "renderers")
- Default renderer is the current one to preserve the backward compatibility, but user can select their own via `NETCFG_TYPE` context variable (e.g., `NETCFG_TYPE=networkd` to enfroce networkd on Debian).
- Added NetworkManager and netplan (nm/networkd) support #170
- FreeBSD live reconfiguration (hotplugged interfaces, resized main disk resizes rootfs)
- Selectable method of how to configure individual interfaces; current static IP configuration is the default, but user can choose to use DHCP via dedicatd context parameters (e.g., `ETH0_METHOD="dhcp"`) #86

Most of the code is in the master (targets 6.2.0), we continue with bugfixing.

**Comment by vholer** [comment]
Selectable guest NIC configuration service/methods implemented in master.

Short description with supported combinations and few OS quirks:
https://github.com/OpenNebula/addon-context-linux/blob/d5e3d3ac93607192cdd85b48cb56e9cf186cbd7b/README.md#guest-network-configuration-since-6180
