### ISSUE TITLE
Fix potential mount/umount issues on FreeBSD 13

### ISSUE THREAD

**Issue by 5u623l20** [OpenNebula/addon-context-linux#230]
- In case the CD-ROM is not mounted "glabel status | grep CONTEXT | awk '{print $3}'" will have a null string which will eventually assign the value "/dev/" to "dev_context" variable. In later occasions while existence of "dev_context" is checked it will always return true and no elif conditions will be executed. Add additional glabel check for BSD.
  - In case the CD-ROM is not mounted and used there is nothing to unmount and eventually trying to unmount will throw error. So add an additional check to see if "MOUNT_DIR" is used as any mount points or not.

Pull request submitted.

https://github.com/OpenNebula/addon-context-linux/pull/229

**Comment by vholer** [comment]
Merged, thank you very much for improvements!
