### ISSUE TITLE
Do not try to configure an interface if it's not found

### ISSUE THREAD

**Issue by jfontan** [OpenNebula/addon-context-linux#26]
Bug found in https://forum.opennebula.org/t/nic-reattach-on-sunstone-breaks-etc-network-interfaces/1599/3

Even if the interface is not found the information for the interface is added to the configuration file without device name:

```
iface  inet static
  address ...
  network ...
  netmask ...
  gateway ...
```

**Comment by nikksno** [comment]
Nice work! Thank you!
