### ISSUE TITLE
Allow user to disable automatic Swap mounting

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/addon-context-linux#260]
By looking at the script `loc-14-mount-swap`, we can see that there's no way the user can tell the script to not mount Swap partition automatically.

It would be convenient to be able to add a Context Variable on the VM that would allow to not mount the Swap partition.

For example, adding `DISABLE_SWAP` with the value `true` could make the `loc-14-mount-swap` script to not try to mount the Swap partitions.

**Comment by ospalax** [comment]
Solved by PR: https://github.com/OpenNebula/addon-context-linux/pull/262
