### ISSUE TITLE
Automatically add static route for onegate-proxy

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/addon-context-linux#281]
Hello.

With the new [onegate-proxy](https://docs.opennebula.io/6.6/installation_and_configuration/opennebula_services/onegate.html#advanced-setup) in OpenNebula 6.6, I think that contextualisation should add static address if `ONEGATE_ENDPOINT` point to a link local address:

1. extract `ONEGATE_ENDPOINT` host
2. if the `ONEGATE_ENDPOINT` host is a link local address, add a static route

Thanks.

**Comment by rsmontero** [comment]
Makes total sense, adding for next release. Thanks!

**Comment by tinova** [comment]
Related to #277
