### ISSUE TITLE
'dpkg -i one-context_4.14.4.deb' shows '/etc/init.d/vmcontext' file does not exist error

### ISSUE THREAD

**Issue by thomasalrin** [OpenNebula/addon-context-linux#29]
I'm using ubuntu 14.04

I downloaded the deb from https://github.com/OpenNebula/addon-context-linux/releases/download/v4.14.4/one-context_4.14.4.deb

when i try to install this package using 'dpkg -i one-context_4.14.4.deb', it thows  '/etc/init.d/vmcontext' file does not exist error.

To resolve this problem, now i copy and paste all the scripts to my image.

```
root@tom:~# dpkg -i one-context_4.14.3.deb 
(Reading database ... 51873 files and directories currently installed.)
Preparing to unpack one-context_4.14.3.deb ...
Unpacking one-context (4.14.3) over (4.14.3) ...
Setting up one-context (4.14.3) ...
`update-rc.d: /etc/init.d/vmcontext: file does not exist`
Processing triggers for ureadahead (0.100.0-16) ...

```

root@tom-resize:/etc/init.d# nano vmcontext
root@tom-resize:/etc/init.d# dpkg -i /root/one-context_4.14.3.deb 
(Reading database ... 51873 files and directories currently installed.)
Preparing to unpack /root/one-context_4.14.3.deb ...
Unpacking one-context (4.14.3) over (4.14.3) ...
Setting up one-context (4.14.3) ...
 System start/stop links for /etc/init.d/vmcontext already exist.

**Comment by jfontan** [comment]
I am not able to reproduce it. Please, open it again if it continues to happen.
