### ISSUE TITLE
Fedora random boot freeze, Fedora 38 pending 

### ISSUE THREAD

**Issue by xorel** [OpenNebula/addon-context-linux#301]
We noticed that Fedora37 with one-context 6.6.1 randomly freezes in early-stage boot (~1% of boot).
We should address this issue together with introducing Fedora 38.

![fedora_freeze](https://github.com/OpenNebula/addon-context-linux/assets/1098246/9980c2de-4495-44e9-b3de-17db91b55ef5)

**Comment by codyro** [comment]
This may be related to https://rwmj.wordpress.com/2023/06/14/i-booted-linux-292612-times/

**Comment by xorel** [comment]
Thank you for pointing this out, looks relevant.

**Comment by xorel** [comment]
Fedora 38 appliance released. I am closing this issue as the boot freeze is almost certainly a kernel bug.
![image](https://github.com/OpenNebula/addon-context-linux/assets/1098246/3c3e433f-0922-454a-90e4-d4c417a6ea83)
