### ISSUE TITLE
Add static routes

### ISSUE THREAD

**Issue by mdrasheek** [OpenNebula/addon-context-linux#305]
Hello,

We're facing a challenge in adding a static route via one-context and we're seeking guidance on the process.

Here's the context: We previously established a static route on a production server using the "ip route" command. Additionally, we included this route in "rc.local" to ensure its persistence during startup. However, a situation arose when a team member attempted to add an SSH key via context. Strangely, this action triggered a network restart (the reason behind this behavior is unclear). Unfortunately, this restart caused the previously added route to disappear, subsequently affecting our services.

Could you kindly provide insights on how to circumvent this issue? Additionally, if we need to configure a static route using the nebula context, could you guide us through the process?

Thank you in advance for your assistance.

**Comment by dann1** [comment]
Hello, please create a post at [forum.opennebula.org](https://forum.opennebula.io/) and tag it with _Context_. Let's discuss this over there, with the help of the full community. The issues in this repository exist to report bugs and request features.
