### ISSUE TITLE
Deb package depends ifupdown or ifupdown2 even if netplan is installed instead

### ISSUE THREAD

**Issue by stanlog** [OpenNebula/addon-context-linux#306]
Hello,
To install one-context deb package, ifupdown or ifupdown2 need to be installed, even if the VM uses netplan + networkd instead of the default Debian network management package. In the same way, one-context uses resolv.conf, even if systemd-resolved is installed (no configuration performed in netplan yaml file on boot by context).
It would be great than one-context manages this case.

**Comment by dann1** [comment]
One of the things we want to support is the ability to switch between any of the supported network renderers at any given time with the NETCFG_TYPE variable. For this one-context needs several dependencies installed, even though the VM by default wouldn't need some package.

**Comment by stanlog** [comment]
Ok, thank you @dann1.
I will open another issue maybe later to know if it could be possible when netplan is selected in NETCFG_TYPE to write nameservers informations in 50-one-context.yaml file, and drive DNS conf through systemd-resolved (if it's not complicated to code).
