### ISSUE TITLE
AlmaLinux 9 and Opennebula 6.4.x

### ISSUE THREAD

**Issue by AT-SGAI-CSIC** [OpenNebula/addon-context-linux#308]
Hi, we would like to use contextualization in Opennebula 6.4.x with AlmaLinux 9. We see that for Opennebula 6.4.x AL9 it's not supported?  Which package version should we use?

Thank you.

**Comment by AT-SGAI-CSIC** [comment]
We have resolved the issue:

`# dnf install almalinux-release-opennebula-addons`

`# dnf  search --showduplicates one-context`

![imagen](https://github.com/OpenNebula/addon-context-linux/assets/139878963/eb46e69e-73d0-4c60-b06e-53929d0ae125)

and finally:

`# dnf install one-context-6.4.0-1.el9.noarch`

The compilation is made by AL, on the other hand ON doesn't reflect in the documentation that AL9 it's working with one-context 6.4.x:

https://docs.opennebula.io/6.4/management_and_operations/references/kvm_contextualization.html#id2

It would be interesting to update this aspect ...

**Comment by dann1** [comment]
rhel9 support was added on [Context Package 6.6.0](https://github.com/OpenNebula/addon-context-linux/releases/tag/v6.6.0) release. You can use that package on 6.4, the naming simply indicates the timing of the release, there is no strictness enforced, unless stated.
