### ISSUE TITLE
Do not overwrite network/resolv configuration when network context is disabled

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/addon-context-linux#32]
Hello,

If I disable network context on a template, the ``/etc/network/interfaces`` and ``/etc/resolv.conf`` are overwritten.

Regards.

**Comment by baby-gnu** [comment]
I kept the SSH contextualisation, without it the files are not overwritten.

**Comment by jfontan** [comment]
I also think this should be done.

**Comment by jfontan** [comment]
DNS configuration was already skipped if there was no info in the context
