### ISSUE TITLE
VM startup won't report READY=YES to OneGate (authentication issue)

### ISSUE THREAD

**Issue by tkald** [OpenNebula/addon-context-linux#45]
Seems like context package 5.0 don't authenticate with token to report ready state to onegate.

From opennebula onegate log:
```
------
Tue Jun 21 01:15:51 2016 [E]: X_ONEGATE_TOKEN header not preset
Tue Jun 21 01:15:51 2016 [I]: Unauthorized login attempt
Tue Jun 21 01:15:51 2016 [I]: 192.168.17.200 - - [21/Jun/2016:01:15:51 +0300] "PUT /vm HTTP/1.1" 401 14 0.0016
------
```
VM (ubuntu 16.04) context log:
`
Waiting one minute to reconfigure the machine
Waiting one minute to reconfigure the machine
Reconfiguring
diff: /tmp/context.sh: No such file or directory
Reconfiguring
NOCHANGE: partition 2 could only be grown by 2015 [fudge=2048]
/sbin/ifdown: interface eth0 not configured
/usr/bin/onegate.rb:21:in <module:CloudClient>': undefined method +' for nil:NilClass (NoMethodError)
        from /usr/bin/onegate.rb:13:in <main>'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100    23  100    14  100     9   2356   1514 --:--:-- --:--:-- --:--:--  2800
Not authorized
`
In VM /tmp/one_env file does have TOKENTXT variable present.

Also allready contextualized VM with persistent disks and waits for network to come up too long. 
This does not happen on 1st boot.
![boot](https://cloud.githubusercontent.com/assets/8062491/16228283/cffb713a-37be-11e6-8198-2c2fe0edf4b8.png)

**Comment by jmelis** [comment]
Probably related to the environment variables
