### ISSUE TITLE
In Ubuntu grub configures serial tty not supported by ONE

### ISSUE THREAD

**Issue by jfontan** [OpenNebula/addon-context-linux#53]
Serial TTY should be unconfigured so kernel upgrades don't render the VM unbootable.

**Comment by FlorianHeigl** [comment]
I've configured my VMs to have a serial console; ok if i prepare something that does a dual console setup? it works even on linux these days.

**Comment by jfontan** [comment]
What do you mean by a dual console setup?

**Comment by FlorianHeigl** [comment]
one that puts a console on vga and another on ttyS1.
both will be active. so you can virsh attach one-123 for serial, and vnc for vga.

**Comment by lgrawet** [comment]
I totally agree with FlorianHeigl on this one, I also use a dual console setup (vga+serial). I also disable console blanking.

GRUB_CMDLINE_LINUX="consoleblank=0 console=ttyS0,115200n8 console=tty0"
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"
