### ISSUE TITLE
IPv6 is not currently supported

### ISSUE THREAD

**Issue by jmelis** [OpenNebula/addon-context-linux#54]
IP6_ULA generated by IPv6 address ranges is not supported

**Comment by feldsam** [comment]
On redhat it is `IPV6ADDR_SECONDARIES=ula_ipv6_address ` option in ifcfg-* file

On debian is need to add second section

	iface eth0 inet6 static
	        address ula_ipv6_address
	        netmask 64

**Comment by vholer** [comment]
There are more context variables, which needs to be fixed and/or supported for next OpenNebula release:

* ETHx_IP6, ETHx_IP6_ULA, ETHx_IP6_PREFIX_LENGTH
* PCIx_IP6, PCIx_IP6_ULA, PCIx_IP6_PREFIX_LENGTH
