### ISSUE TITLE
Split contextualisation scripts in two parts

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/addon-context-linux#60]
Hello,

I think we could split the contextualisation scripts in two parts:

- what should be done before the network is UP (setting configuration parameters like network, hostname, etc.)
- what should be done when the system is running, i.e after `multi-user.target` (like `$START_SCRIPT`)

Regards.

**Comment by FlorianHeigl** [comment]
@baby-gnu using DNS_HOSTNAME the network has to be up before the hostname can be found.
I played around with a systemd unit for the context, and the best working version did:
After=network 
Before=ssh

This avoids some major race conditions but even then you can have apache or databases start up with an invalid hostname.
I left the 'service network restart' in the network context intact for this reason.
Haven't seen bad consequences like this anymore.

The second part  (multi-user) is very desirable, yeah.

**Comment by baby-gnu** [comment]
I made some tests and I have the following `.service` for contextualisation:

```
[Unit]
# Remove default dependencies or it will not work
DefaultDependencies=no

# We wants network-pre.target as we are a provider
# See man systemd.special(7) - SPECIAL PASSIVE SYSTEM UNITS
Before=network-pre.target
Wants=network-pre.target

# Make sure to have filesystem mounted since we remove default dependencies.
After=local-fs.target

...

[Install]
WantedBy=networking.service
```

and the second part is much more simple:

```
[Unit]
After=multi-user.target

...

[Install]
WantedBy=multi-user.target
```

**Comment by vholer** [comment]
Hi @baby-gnu and @FlorianHeigl, by older commit 93cb488ffdd66f3360a1fe1235807d17be51af6d I tried to split the contextualization scripts into pre and post networking. For now, only the Systemd is done, the SysV init scripts needs to be fixed before next release. Just letting you know in case you want to try it or discuss the change. Thank you!

**Comment by FlorianHeigl** [comment]
Thx @vholer i very much want to test them!

**Comment by vholer** [comment]
The second part (SysV and Upstart) is covered by recent PR #74. I think it's done for now and I'll close this issue. If you experience any problem (at least I think there is still space for play with the init script dependencies), please open a new one. Thank you!
