### ISSUE TITLE
Contextualize on each boot

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#65]
There is a check in /usr/sbin/one-contextd which prevents subsequent contextualizations, until the context ISO changes. It should be aligned with Windows context. to run on each boot. State files should be also moved from /tmp somewhere in /var (e.g. /var/run?) .

**Comment by FlorianHeigl** [comment]
@vholer /var/run or /var/tmp should both be nice, /var/run is not persistent, /var/tmp has to be (but people sometimes mess it up). I think everyone would also like a /var/lib/one-context.d if they are needed persistently, and it has the benefit of being able to close permissions to root only, if needed?

**Comment by vholer** [comment]
Again, by older monster commit 93cb488ffdd66f3360a1fe1235807d17be51af6d we have introduced the /var/run/one-context/ directory for state files. For all our current data, the non-persistent location is fine.

But I can also add the persistent location, e.g. if START_SCRIPT needs to be run only once and lock file preserving the reboots is needed. Do you have any other use cases for the persistent directory, @FlorianHeigl ?

**Comment by vholer** [comment]
(... otherwise this issue was to fix the contextualization to be run on each boot and it's fixed now.)

**Comment by FlorianHeigl** [comment]
Hi @vholer Sorry I haven't given feedback - I also think I don't have a use case ready right now.
