### ISSUE TITLE
Sometimes the CONTEXT volume is not available when vmcontext starts

### ISSUE THREAD

**Issue by phroton** [OpenNebula/addon-context-linux#7]
At 2-3 of 8 newly instantiated VMs on our environment (Opennebula with StorPool Integration), the CONTEXT volume is not available when vmcontext starts.

I added a hotfix and simple logging to our environment:
https://github.com/phroton/addon-context-linux/commit/0aea9c04e630cfbf672f65d61e568231f47979eb

Could be done better, but works for us.

**Comment by jfontan** [comment]
This issue is related to these other ones in redmine:

* http://dev.opennebula.org/issues/3749
* http://dev.opennebula.org/issues/3365

We think all these problems can be fixed using the `blkid` method described in the last link.

**Comment by jfontan** [comment]
I've generated a new test package. Can you check that it works for you?

https://transfer.sh/oRuHN/one-context-4.13.0.rpm

**Comment by jfontan** [comment]
Checked that this change fixes the problem in CentOS 7
