### ISSUE TITLE
Add netplan support

### ISSUE THREAD

**Issue by cwxda** [OpenNebula/addon-context-linux#87]
Ubuntu 17.10 no longer uses /etc/network/interfaces, but netplan instead.
The context scripts won't configure network anymore atm

**Comment by vholer** [comment]
For this moment, you can fallback to the legacy `ifupdown` package and use Ubuntu 17.10 same way as previous systems configured via `/etc/network/interfaces`. This approach still works.

**Comment by trenton42** [comment]
This workaround no longer works in the upcoming 20.04 LTS release

**Comment by vholer** [comment]
Hello @trenton42 , is the `ifupdown` package going to be removed in 20.04 or the legacy scripts just stopped working. In both cases, a reference to the announcement (mailing list) or bugreport (in Ubuntu) would help us understand the problem to make the decision. Thank you! Vlastimil

**Comment by trenton42** [comment]
I think I spoke to soon, there was something else going on that prevented the legacy script from working. The `ifupdown` package is still available in `20.04`, and the legacy script still works.

**Comment by openmilanese** [comment]
Test my personal netplan support. I forked today master branch and rewrite the patch. I have tested and it work ipv4 principal nic. Still pending for pull request review!

**Comment by trenton42** [comment]
Linking the PR from @openmilanese: #192

**Comment by openmilanese** [comment]
I redone the tests for ipv4 with the new version. I made some corrections that I had forgotten. It works for me. I await feedback.

**Comment by vholer** [comment]
Netplan support as part of #227
