### ISSUE TITLE
Swap is only activated on first boot

### ISSUE THREAD

**Issue by lgrawet** [OpenNebula/addon-context-linux#90]
Hi,

Swap is only activated on first boot. On every subsequent boot, if context hasn't changed, context scripts aren't executed and swap isn't activated.

Best regards,

Laurent

**Comment by lgrawet** [comment]
Also note that one-contextd is executed on every boot on Debian systems because /tmp content is removed on every boot. swap is then activated on every boot.

This is not the case for CentOS/RHEL systems (unless there is a context change because /tmp data remains)

**Comment by vholer** [comment]
Hi @lgrawet,

you are using old contextualization scripts. Please check some more recent https://github.com/OpenNebula/addon-context-linux/releases. These are already using `/var/run/one-context/` for state files, then the contextualization is done on each boot.

Best regards,
Vlastimil Holer

**Comment by lgrawet** [comment]
Hi,

OK sorry, I've checked the code on github before reporting but missed this part ;-)
I still haven't updated context packages because I read in the release notes IPv6 contextualization is compatible with OpenNebula 5.4+ and I'm still running 5.2.
