### ISSUE TITLE
Acpid dependency

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-linux#97]
Moved from https://github.com/OpenNebula/addon-context-alpine/issues/6 - FlorianHeigl commented 14 days ago:
We should probably by default install acpi and enable it, unless we're in a xen pv domU.(Or just disable it on first boot if /proc/xen is present)For anything else, OpenNebula doesn't know how to shut it down (not exposed by hypervisor & no event channel)It seems by default, without acpi(d) alpine won't do a shut down action on power button press. Could someone confirm?

**Comment by vholer** [comment]
The `acpid` should be part of the `busybox`, which is a base for the Alpine, right?
So the only problem should be not having the `acpid` enabled.

BTW, running `acpid` @ domU has any negative impact? Or, is it just a best practice not to enable an unnecessary service? Just curious.

**Comment by FlorianHeigl** [comment]
@vholer I don't remember well enough, likely the daemon would fail on start if it can't find acpi supporting "hardware". likely totally ok to do it by default and fix if someone tells you it threw errors.

**Comment by vholer** [comment]
I'm closing this, we don't have any problems with having `acpid` running on boot on currently supported HVs.
